install.packages ("BiocManager")

BiocManager::install("devtools")
BiocManager::install("Seurat")
BiocManager::install("SingleCellExperiment")
BiocManager::install("tidyverse")
BiocManager::install("scater")
BiocManager::install("ggplot2")
BiocManager::install("ggpubr")


devtools::install_github("mluetge/ExploreSCdataSeurat3", auth_token="e1514cce2fa6a231bc796d53e27ba6e0ec01f484")

devtools::install_github("mluetge/runSeurat3", auth_token="e1514cce2fa6a231bc796d53e27ba6e0ec01f484")


library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)


# New Version

library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)
library(RColorBrewer)
library(EnhancedVolcano)
library(rmarkdown)
library(workflowr)
library(textshaping)
library(wordcloud)
library(pathview)

```
