---
title: "Comparison Male vs. Female - Stratification of acute Myocarditis patients by sex"
author: "Emily Payne"
date: "2024-10-25"
output: html_document
---
```{r setup, include = FALSE, fig.path = "custom/path", warning = FALSE, message = FALSE}

options (width = 100)
knitr::opts_chunk$set(warning = FALSE, echo = TRUE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234

```



```{r load libraries, echo=FALSE, message=FALSE, warning=FALSE}

suppressPackageStartupMessages({
  library(ExploreSCdataSeurat3)
  library(runSeurat3)
  library(Seurat)
  library(ggpubr)
  library(pheatmap)
  library(SingleCellExperiment)
  library(dplyr)
  library(tidyverse)
  library(viridis)
  library(muscat)
  library(circlize)
  library(destiny)
  library(scater)
  library(metap)
  library(multtest)
  library(clusterProfiler)
  library(org.Hs.eg.db)
  library(msigdbr)
  library(enrichplot)
  library(DOSE)
  library(grid)
  library(gridExtra)
  library(ggupset)
  library(VennDiagram)
  library(NCmisc)
  library(RColorBrewer)
  library(EnhancedVolcano)
  library(textshaping)
  library(wordcloud)
  library(pathview)
  library(workflowr)
})

```





```{r load merged file}

##load merged file 
seuratM <- readRDS("~/Desktop/Emily/Myocarditis snRNAseq/data/01 Merged Seurat files/seuratM_all_metadata_withAMvsHealthy_ventricle_sex_TC con_27.10.2024.rds")

table(seuratM$dataset)
table(seuratM$patient)
table(seuratM$RNA_snn_res.0.25)
table(seuratM$sex)
table(seuratM$orig.ident)

```


```{r Define Cluster Name}


seuratM$clusterName <- "clusterName"

seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "0" )] <- "Fb1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "1" )] <- "BEC1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "2" )] <- "PeriFb1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "3" )] <- "Cardiomyocyte"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "4" )] <- "MCP1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "5" )] <- "TC"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "6" )] <- "MCP2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "7" )] <- "BEC2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "8" )] <- "VSMC"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "9" )] <- "NC"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "10" )] <- "INT1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "11" )] <- "Fb2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "12" )] <- "Fb3"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "13" )] <- "PeriFb2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "14" )] <- "PeriFb3"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "15" )] <- "AdipoC"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "16" )] <- "Unknown"


colclusterName <- c("#D53E4F", "#f4a582", "#FEE08B","#feb24c","#67001f", "#01665e","#66C2A5","#c7eae5","#BEAED4", "#355C7D","#3288BD","#8c510a" ,"#fde0dd","#B45B5C","#dd1c77")

                    
names(colclusterName) <- c("Cardiomyocyte","Fb1","Fb2","Fb3", "INT1", "PeriFb1", "PeriFb2", "VSMC","NC", "BEC1","BEC2", "AdipoC", "MCP1","MCP2","TC")
Idents(seuratM) <- seuratM$clusterName
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, label = TRUE, cols= colclusterName)

```




```{r Create DimPlot with umap}

Idents(seuratM) <- seuratM$sex
DimPlot(seuratM, reduction = "umap", split.by = "sex")


colsex <- c("#dd1c77","#355C7D")
names(colsex) <- c("female", "male")

#subset AM group in TC High, Intermediate, Low, Vlow

seuratAM <- subset(seuratM, pat_sub == "AM")
table(seuratAM$orig.ident)
table(seuratAM$sex)
Idents(seuratAM) <- seuratAM$sex
DimPlot(seuratAM, reduction = "umap", pt.size = 0.1, raster=FALSE, group.by = "sex", cols = colsex)


```


```{r Find DE genes for each sex}

DEGenesAM_sex <- FindAllMarkers(seuratAM, only.pos = TRUE, logfc.threshold = 0.2) %>%
  dplyr::filter(p_val_adj < 0.01)

#head(DEGenes_AM_sex)

#write.table(DEGenes_AM_sex, file= "/Users/immbio/Desktop/Emily/Myocarditis snRNAseq/docs/Markers/DEGenes_AM_sex_only positive markers", sep="\t",quote=F,row.names=F,col.names=T)

##adjust table
DEGenesAM_sex <- DEGenesAM_sex %>% 
  mutate(Gene=gene) %>%
  mutate(gene=gsub("^.*\\.", "", Gene))  %>%
  mutate(EnsID=gsub("\\..*","", Gene))

#View(DEGenesAM_sex)

```


```{r Females}


## DE Genes for females with AM
DEGenesAM_female <- DEGenesAM_sex %>% filter(cluster == "female")

head(DEGenesAM_female)
#View(DEGenesAM_female)

egoAM_female <- enrichGO(gene = unique(DEGenesAM_female$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoAM_female <- setReadable(egoAM_female, OrgDb = org.Hs.eg.db)
barplot(egoAM_female, 
        drop = TRUE, 
        showCategory = 7, 
        title = "Females with Acute Myocarditis",
        font.size = 10)

#View(egoAM_female@result)

```
```{r Dotplot females, fig.width=18, fig.height = 12}

dotplot(egoAM_female, showCategory=20, title = "Females with Acute Myocarditis", font.size = 14)

```


```{r Males}

## DE Genes for males with AM
DEGenesAM_male <- DEGenesAM_sex %>% filter(cluster == "male")

head(DEGenesAM_male)
#View(DEGenesAM_male)

egoAM_male <- enrichGO(gene = unique(DEGenesAM_male$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoAM_male <- setReadable(egoAM_male, OrgDb = org.Hs.eg.db)

barplot(egoAM_male, 
        drop = TRUE, 
        showCategory = 7, 
        title = "Males with Acute Myocarditis",
        font.size = 10)

#View(egoAM_male@result)

```

```{r Dotplot male,  fig.width = 16, fig.height = 12}

dotplot(egoAM_male, showCategory=30, title = "Males with Acute Myocarditis", font.size = 14)


```


```{r DE genes posive and negative for Volcano Plot}

DEGenes_AM_sex <- FindAllMarkers(seuratAM, only.pos = FALSE, logfc.threshold = 0.2) %>%
  dplyr::filter(p_val_adj < 0.01)

#head(DEGenes_AM_sex)

#write.table(DEGenes_AM_sex, file= "/Users/immbio/Desktop/Emily/Myocarditis snRNAseq/docs/Markers/DEGenes_AM_sex_positive and negative markers", sep="\t",quote=F,row.names=F,col.names=T)

##adjust table
DEGenesAM_sex <- DEGenesAM_sex %>% 
  mutate(Gene=gene) %>%
  mutate(gene=gsub("^.*\\.", "", Gene))  %>%
  mutate(EnsID=gsub("\\..*","", Gene))


```

```{r Volcano Plot of DE Genes for Females, fig.width = 20, fig.height = 20}


##Volcano Plot for DE genes in females
DEGenesAM_female <- DEGenes_AM_sex %>% filter(cluster == "female")
#head(DEGenesAM_female)

DEGenesAM_female <- DEGenesAM_female %>% 
  mutate(Gene=gene) %>%
  mutate(gene=gsub("^.*\\.", "", Gene))  %>%
  mutate(EnsID=gsub("\\..*","", Gene))

res_female <- as.data.frame(DEGenesAM_female)


EnhancedVolcano(res_female, 
                x = 'avg_log2FC',
                y = 'p_val_adj',
                lab = res_female$gene,
                # xlim =c(-6, 6), 
                title = "DE Genes Females with AM",
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-1,
                FCcutoff = 1.5,
    cutoffLineType = 'twodash',
    cutoffLineWidth = 0.8,
    pointSize = 2.0,
    labSize = 6.0,
    # shape = c(1,4, 23,25),
    colAlpha = 1,
    legendLabels=c('Not sig.','Log (base 2) FC','p-value',
      'p-value & Log (base 2) FC'),
    legendPosition = 'right',
    legendLabSize = 12,
    legendIconSize = 2.0,
    # drawConnectors = TRUE,
    # widthConnectors = 0.75,
    # ridlines.major = FALSE,
    gridlines.minor = FALSE)


top_genes_AM <- DEGenesAM_female %>% 
  filter(p_val_adj < 0.05, abs(avg_log2FC) > 1) %>% 
  arrange(p_val_adj) %>% 
  slice_head(n = 30) %>% 
  pull(gene)

```


```{r Volcano Plot for DE genes in male, fig.width = 20, fig.height = 20}

##Volcano Plot for DE genes in males
DEGenesAM_male <- DEGenes_AM_sex %>% filter(cluster == "male")
#head(DEGenesAM_male)

DEGenesAM_male <- DEGenesAM_male %>% 
  mutate(Gene=gene) %>%
  mutate(gene=gsub("^.*\\.", "", Gene))  %>%
  mutate(EnsID=gsub("\\..*","", Gene))

res_male <- as.data.frame(DEGenesAM_male)

EnhancedVolcano(res_male, 
                x = 'avg_log2FC',
                y = 'p_val_adj',
                lab = res_male$gene,
                # selectLab = c('gene),
                #xlim =c(-6, 6), 
                title = "DEGenes Males with AM",
                xlab = bquote(~Log[2]~ 'fold change'),
                pCutoff = 10e-1,
                FCcutoff = 1.5,
                cutoffLineType = 'twodash',
                cutoffLineWidth = 0.8,
                pointSize = 2.0,
                labSize = 6.0,
                # shape = c(1,4, 23,25),
                colAlpha = 1,
                legendLabels=c('Not sig.','Log (base 2) FC','p-value',
                               'p-value & Log (base 2) FC'),
                legendPosition = 'right',
                legendLabSize = 12,
                legendIconSize = 2.0,
                #drawConnectors = TRUE,
                # widthConnectors = 0.75,
                # ridlines.major = FALSE,
                gridlines.minor = FALSE)


top_genes_AM_male <- DEGenesAM_male %>% 
  filter(p_val_adj < 0.05, abs(avg_log2FC) > 1) %>% 
  arrange(p_val_adj) %>% 
  slice_head(n = 30) %>% 
  pull(gene)


```



```{r}

Idents(seuratM) <- seuratM$pat_sub
seuratAM <- subset(seuratM, pat_sub == "AM")
levels(seuratAM)
table(seuratAM$orig.ident)

seuratAM_immun <- subset(seuratAM, clusterName %in% c("MCP1", "MCP2","TC", "Fb1", "Fb2", "Fb3", "INT1", "PeriFb2", "Cardiomyocyte"))
table(seuratAM_immun$orig.ident)
table(seuratAM_immun$patient, seuratAM_immun$sex)
table(seuratAM_immun$TC, seuratAM_immun$sex)
table(seuratAM_immun$sex)
table(seuratAM_immun$clusterName, seuratAM_immun$sex)

Idents(seuratAM_immun) <- seuratAM_immun$sex

colsex <- c("#dd1c77","#355C7D")
names(colsex) <- c("female", "male")
            

DimPlot(seuratAM_immun, reduction = "umap", pt.size = 0.3, cols = colsex)

colcluster<- c("#D53E4F", "#f4a582", "#FEE08B","#feb24c","#67001f" , "#66C2A5", "#fde0dd","#B45B5C","#dd1c77")

                    
names(colcluster) <- c("Cardiomyocyte","Fb1", "Fb2","Fb3", "INT", "PeriFb2", "MCP1","MCP2","TC")

Idents(seuratAM_immun) <- seuratAM_immun$clusterName

DimPlot(seuratAM_immun, reduction = "umap", cols = colcluster, pt.size = 0.3)


```





```{r}

date()
sessionInfo()



```


```

